export const INIT_MY_LIBRARY = 'INIT_MY_LIBRARY'
export const POST_PLAYLIST = 'POST_PLAYLIST'
export const POST_PRIVATE_TRACK = 'POST_PRIVATE_TRACK'
export const PUT_TRACK_TO_PLAYLIST = 'PUT_TRACK_TO_PLAYLIST'