export const REGISTER_LOGIN_USER = 'REGISTER_LOGIN_USER'
export const UPDATE_USER_LANGUAGE = 'UPDATE_USER_LANGUAGE'
export const UPDATE_USER_COUNTRY = 'UPDATE_USER_COUNTRY'
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS'
